### ISSUE TITLE
In-Wall Aqara Switches

### ISSUE THREAD

**Issue by nextmoov-ops** [thomashermine/home-assistant-config#52]
See : 
https://www.zigbee2mqtt.io/devices/QBKG12LM.html

## Pairing

Push on the left-hand side button for 10 secs.
Do NOT stop pushing till lights becomes blue.

## Decoupled Mode

https://www.zigbee2mqtt.io/devices/QBKG12LM.html#decoupled-mode

Encoded Payload (compatible w/ HA Developer Tools > Service): 
``

**Comment by thomashermine** [comment]
Replaced by Notion Documentation
